#!/data/data/com.termux/files/usr/bin/bash -e

EXTRA_ARGS=""
if [[ ! -z $1 ]]; then
    EXTRA_ARGS=$1
    if [[ $EXTRA_ARGS != "--no-check-certificate" ]]; then
        EXTRA_ARGS=""
    fi
fi

    CHROOT=kali-arm64

function check_dependencies() {
    printf "${blue}\n[*] Checking package dependencies...${reset}\n"
    apt-get update -y &> /dev/null || apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" dist-upgrade -y &> /dev/null
termux-setup-storage
    for i in proot tar pulseaudio wget; do
        if [ -e $PREFIX/bin/$i ]; then
            echo "  $i is OK"
        else
            printf "Installing ${i}...\n"
            apt install -y $i || {
                printf "${red}ERROR: Failed to install packages.\n Exiting.\n${reset}"
                exit
            }
        fi
    done
    apt upgrade -y
}


function sound_setup() {
 
    printf "${blue}[*] Configuring Pulseaudio...${reset}\n\n"
        DEFAULT_PA=$PREFIX/etc/pulse/default.pa
        cat > $DEFAULT_PA <<- EOF
#!/data/data/com.termux/files/usr/bin/pulseaudio -nF
#
# This file is part of PulseAudio.
#
# PulseAudio is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# PulseAudio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with PulseAudio; if not, see <http://www.gnu.org/licenses/>.

# This startup script is used only if PulseAudio is started per-user
# (i.e. not in system mode)

.fail

### Automatically restore the volume of streams and devices
load-module module-device-restore
load-module module-stream-restore
load-module module-card-restore

### Automatically augment property information from .desktop files
### stored in /usr/share/application
load-module module-augment-properties

### Should be after module-*-restore but before module-*-detect
load-module module-switch-on-port-available

### Load audio drivers statically
### (it's probably better to not load these drivers manually, but instead
### use module-udev-detect -- see below -- for doing this automatically)
#load-module module-null-sink
#load-module module-pipe-sink

### Automatically load driver modules depending on the hardware available
.ifexists module-detect.so
### Use the static hardware detection module (for systems that lack udev support)
#load-module module-detect
.endif

### Automatically connect sink and source if JACK server is present
.ifexists module-jackdbus-detect.so
.nofail
load-module module-jackdbus-detect channels=2
.fail
.endif


### Load several protocols
.ifexists module-esound-protocol-unix.so
load-module module-esound-protocol-unix
.endif
load-module module-native-protocol-unix

### Network access (may be configured with paprefs, so leave this commented
### here if you plan to use paprefs)
#load-module module-esound-protocol-tcp
load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1

### Load the RTP receiver module (also configured via paprefs, see above)
#load-module module-rtp-recv

### Load the RTP sender module (also configured via paprefs, see above)
#load-module module-null-sink sink_name=rtp format=s16be channels=2 rate=44100 sink_properties="device.description='RTP Multicast Sink'"
#load-module module-rtp-send source=rtp.monitor


### Automatically restore the default sink/source when changed by the user
### during runtime
### NOTE: This should be loaded as early as possible so that subsequent modules
### that look up the default sink/source get the right value
load-module module-default-device-restore

### Make sure we always have a sink around, even if it is a null sink.
load-module module-always-sink

### Honour intended role device property
load-module module-intended-roles

### Automatically suspend sinks/sources that become idle for too long
load-module module-suspend-on-idle

### If autoexit on idle is enabled we want to make sure we only quit
### when no local session needs us anymore.
.ifexists module-console-kit.so
load-module module-console-kit
.endif
.ifexists module-systemd-login.so
load-module module-systemd-login
.endif

### Enable positioned event sounds
load-module module-position-event-sounds

### Cork music/video streams when a phone stream is active
load-module module-role-cork

### Modules to allow autoloading of filters (such as echo cancellation)
### on demand. module-filter-heuristics tries to determine what filters
### make sense, and module-filter-apply does the heavy-lifting of
### loading modules and rerouting streams.
load-module module-filter-heuristics
load-module module-filter-apply

### Make some devices default
#set-default-sink output
#set-default-source input

### Allow including a default.pa.d directory, which if present, can be used
### for additional configuration snippets.
### Note that those snippet files must have a .pa file extension, not .conf
.nofail
.include /data/data/com.termux/files/usr/etc/pulse/default.pa.d
load-module module-sles-sink
#load-module module-aaudio-sink
EOF
DAEMON_CONF=$PREFIX/etc/pulse/daemon.conf
cat > $DAEMON_CONF <<- EOF
# This file is part of PulseAudio.
#
# PulseAudio is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# PulseAudio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with PulseAudio; if not, see <http://www.gnu.org/licenses/>.

## Configuration file for the PulseAudio daemon. See pulse-daemon.conf(5) for
## more information. Default values are commented out.  Use either ; or # for
## commenting.

; daemonize = no
; fail = yes
; allow-module-loading = yes
; allow-exit = yes
; use-pid-file = yes
; system-instance = no
; enable-shm = yes
; enable-memfd = yes
; shm-size-bytes = 0 # setting this 0 will use the system-default, usually 64 MiB
; lock-memory = no
; cpu-limit = no

; high-priority = yes
; nice-level = -11

; realtime-scheduling = yes
; realtime-priority = 5

; exit-idle-time = -1
; scache-idle-time = 20

; dl-search-path = (depends on architecture)

; load-default-script-file = yes
; default-script-file = /data/data/com.termux/files/usr/etc/pulse/default.pa

; log-target = auto
; log-level = notice
; log-meta = no
; log-time = no
; log-backtrace = 0

; resample-method = speex-float-1
; avoid-resampling = false
; enable-remixing = yes
; remixing-use-all-sink-channels = yes
; remixing-produce-lfe = no
; remixing-consume-lfe = no
; lfe-crossover-freq = 0

; flat-volumes = no

; rescue-streams = yes

; rlimit-fsize = -1
; rlimit-data = -1
; rlimit-stack = -1
; rlimit-core = -1
; rlimit-as = -1
; rlimit-rss = -1
; rlimit-nproc = -1
; rlimit-nofile = 256
; rlimit-memlock = -1
; rlimit-locks = -1
; rlimit-sigpending = -1
; rlimit-msgqueue = -1
; rlimit-nice = 31
; rlimit-rtprio = 9
; rlimit-rttime = 200000

; default-sample-format = s16le
; default-sample-rate = 44100
; alternate-sample-rate = 48000
; default-sample-channels = 2
; default-channel-map = front-left,front-right

; default-fragments = 4
; default-fragment-size-msec = 25

; enable-deferred-volume = yes
; deferred-volume-safety-margin-usec = 8000
; deferred-volume-extra-delay-usec = 0
EOF
}


function create_launcher() {
   
    NH_SHORTCUT=${PREFIX}/bin/nh
    cat > $NH_SHORTCUT <<- EOF
#!/data/data/com.termux/files/usr/bin/bash -e

cd \${HOME}
## termux-exec sets LD_PRELOAD so let's unset it before continuing
unset LD_PRELOAD
## Workaround for Libreoffice, also needs to bind a fake /proc/version
if [ ! -f $CHROOT/root/.version ]; then
    touch $CHROOT/root/.version
fi

## Default user is "kali"
user="kali"
home="/home/\$user"
start="sudo -u kali /bin/bash"

## NH can be launched as root with the "-r" cmd attribute
## Also check if user kali exists, if not start as root
if grep -q "kali" ${CHROOT}/etc/passwd; then
    KALIUSR="1";
else
    KALIUSR="0";
fi
if [[ \$KALIUSR == "0" || ("\$#" != "0" && ("\$1" == "-r" || "\$1" == "-R")) ]];then
    user="root"
    home="/\$user"
    start="/bin/bash --login"
    if [[ "\$#" != "0" && ("\$1" == "-r" || "\$1" == "-R") ]];then
        shift
    fi
fi

cmdline="proot \\
        --link2symlink \\
        -0 \\
        -r $CHROOT \\
        -b /dev \\
        -b /sdcard \\
        -b /proc \\
        -b $CHROOT\$home:/dev/shm \\
        -w \$home \\
           /usr/bin/env -i \\
           HOME=\$home \\
           PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin \\
           TERM=\$TERM \\
           LANG=C.UTF-8 \\
           \$start"

cmd="\$@"
if [ "\$#" == "0" ];then
    exec \$cmdline
else
    \$cmdline -c "\$cmd"
fi
EOF

    
chmod +x $PREFIX/bin/nh

}


function create_kex_launcher() {
    KEX_LAUNCHER=kali-arm64/usr/bin/p
    cat > $KEX_LAUNCHER <<- EOF
#!/bin/bash
        if [ ! -z \$starting_kex ]; then
            printf '\nKesalahan memulai server Vnc.\nSilakan coba nh p kill" atau mulai ulang sesi termux Anda dan coba lagi.\n\n'
            fi
  
    if [ ! -f ~/.vnc/passwd ]; then
        vncpasswd
    fi
    USR=\$(whoami)
    if [ \$USR == "root" ]; then
        SCREEN=":2"
    else
        SCREEN=":1"
    fi

    export HOME=\${HOME}; export USER=\${USR}; export PULSE_SERVER=127.0.0.1; vncserver \$SCREEN >/dev/null 2>&1 </dev/null
    sessions=\$(vncserver -list | sed s/"TigerVNC"/"NetHunter KeX"/)
    if [[ \$sessions == *"590"* ]]; then
        printf "\n\${sessions}\n"
        printf "\nAnda dapat menggunakan klien Vnc untuk terhubung ke salah satu tampilan ini.\n\n" 
        fi
    
    starting_kex=1


EOF
KEX_LAUNCR=kali-arm64/usr/bin/s
    cat > $KEX_LAUNCR <<- EOF
  vncserver -kill :1 2>/dev/null
    vncserver -kill :2 2>/dev/null
    rm ~/.vnc/kali:1.log 2>/dev/null
    rm ~/.vnc/kali:2.log 2>/dev/null
    rm ~/.vnc/kali:1.pid 2>/dev/null
    rm ~/.vnc/kali:2.pid 2>/dev/null
    pkill Xtigervnc
     rm /tmp/.X11-unix/X1 > /dev/null 2>&1
rm /tmp/.X1-lock > /dev/null 2>&1
    rm ~/.vnc/kali:1.log 2>/dev/null
    rm ~/.vnc/kali:2.log 2>/dev/null
    rm ~/.vnc/kali:1.pid 2>/dev/null
    rm ~/.vnc/kali:2.pid 2>/dev/null

EOF



    chmod 700 $KEX_LAUNCHER
    chmod 700 $KEX_LAUNCR
}

function fix_profile_bash() {
    ## Prevent attempt to create links in read only filesystem
    if [ -f ${CHROOT}/root/.bash_profile ]; then
        sed -i '/if/,/fi/d' "${CHROOT}/root/.bash_profile"
    fi
}

function fix_sudo() {
    ## fix sudo & su on start
    chmod +s $CHROOT/usr/bin/sudo
    chmod +s $CHROOT/usr/bin/su
        echo "kali    ALL=(ALL:ALL) ALL" > $CHROOT/etc/sudoers.d/kali

    # https://bugzilla.redhat.com/show_bug.cgi?id=1773148
    echo "Set disable_coredump false" > $CHROOT/etc/sudo.conf
}

function fix_uid() {
    ## Change kali uid and gid to match that of the termux user
    USRID=$(id -u)
    GRPID=$(id -g)
    nh -r usermod -u $USRID kali 2>/dev/null
    nh -r groupmod -g $GRPID kali 2>/dev/null
}
# Add some colours
red='\033[5;31m'
green='\033[5;33m'
yellow='\033[5;32m'
blue='\033[5;34m'
light_cyan='\033[5;96m'
reset='\033[0m'
function ask() {
    # http://djm.me/ask
    while true; do

        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi

        # Ask the question
        printf "${yellow}\n[?] "
        read -p "$1 [$prompt] " REPLY

        # Default?
        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi

        printf "${reset}"

        # Check if the reply is valid
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}

cd $HOME
check_dependencies
if [ -e "kali-arm64" ]; then
    printf "\n${yellow}File atau direktori kali-arm64 ditemukan.\n"
    if ask "Buat Ulang" "N"; then
    rm -rf kali-arm64
    
    wget $EXTRA_ARGS --continue http://kali.download/nethunter-images/current/rootfs/kalifs-arm64-minimal.sha512sum
    wget $EXTRA_ARGS --continue http://kali.download/nethunter-images/current/rootfs/kalifs-arm64-minimal.tar.xz
    sha512sum -c kalifs-arm64-minimal.sha512sum
    proot --link2symlink tar -xf kalifs-arm64-minimal.tar.xz --exclude='dev' ||:
    rm -rf kalifs-arm64-minimal.tar.xz kalifs-arm64-minimal.sha512sum
    fi
else
    echo "File atau direktori kali-arm64 tidak ditemukan. Mengunduh dan menginstal..."

    wget $EXTRA_ARGS --continue http://kali.download/nethunter-images/current/rootfs/kalifs-arm64-minimal.sha512sum
    wget $EXTRA_ARGS --continue http://kali.download/nethunter-images/current/rootfs/kalifs-arm64-minimal.tar.xz
    sha512sum -c kalifs-arm64-minimal.sha512sum
    proot --link2symlink tar -xf kalifs-arm64-minimal.tar.xz --exclude='dev' ||:
    rm -rf kalifs-arm64-minimal.tar.xz kalifs-arm64-minimal.sha512sum
fi
panels(){
##################### Panel #############################
rm -rf ~/kali-arm64/home/kali/.config/xfce4/panel
mkdir -p ~/kali-arm64/home/kali/.config/xfce4/panel
cat <<EOF > ~/kali-arm64/home/kali/.config/xfce4/panel/whiskermenu-1.rc
favorites=xfce4-terminal-emulator.desktop,xfce4-file-manager.desktop,xfce4-web-browser.desktop
recent=
button-icon=kali-panel-menu
button-single-row=false
show-button-title=false
show-button-icon=true
launcher-show-name=true
launcher-show-description=false
launcher-show-tooltip=true
launcher-icon-size=2
hover-switch-category=true
category-show-name=true
category-icon-size=1
sort-categories=false
view-mode=2
default-category=0
recent-items-max=10
favorites-in-recent=true
position-search-alternate=true
position-commands-alternate=false
position-categories-alternate=true
position-categories-horizontal=false
stay-on-focus-out=false
profile-shape=0
confirm-session-command=true
menu-width=605
menu-height=670
menu-opacity=100
command-settings=xfce4-settings-manager
show-command-settings=true
command-lockscreen=xflock4
show-command-lockscreen=false
command-switchuser=dm-tool switch-to-greeter
show-command-switchuser=false
command-logoutuser=xfce4-session-logout --logout --fast
show-command-logoutuser=false
command-restart=xfce4-session-logout --reboot --fast
show-command-restart=false
command-shutdown=xfce4-session-logout --halt --fast
show-command-shutdown=false
command-suspend=xfce4-session-logout --suspend
show-command-suspend=false
command-hibernate=xfce4-session-logout --hibernate
show-command-hibernate=false
command-logout=xfce4-session-logout
show-command-logout=true
command-menueditor=menulibre
show-command-menueditor=false
command-profile=mugshot
show-command-profile=false
search-actions=6

[action0]
name=Man Pages
pattern=#
command=exo-open --launch TerminalEmulator man %s
regex=false

[action1]
name=Search the Web
pattern=?
command=exo-open --launch WebBrowser https://duckduckgo.com/?q=%u
regex=false

[action2]
name=Search for Files
pattern=-
command=catfish --path=~ --start %s
regex=false

[action3]
name=Wikipedia
pattern=!w
command=exo-open --launch WebBrowser https://en.wikipedia.org/wiki/%u
regex=false

[action4]
name=Run in Terminal
pattern=!
command=exo-open --launch TerminalEmulator %s
regex=false

[action5]
name=Open URI
pattern=^(file|http|https):\\/\\/(.*)$
command=exo-open \\0
regex=true
EOF
#
mkdir -p  ~/kali-arm64/home/kali/.config/xfce4/panel/launcher-5
cat <<EOF > ~/kali-arm64/home/kali/.config/xfce4/panel/launcher-5/16915437661.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Firefox ESR
Comment=Browse the World Wide Web
Exec=/usr/lib/firefox-esr/firefox-esr %u
Icon=firefox-esr
Path=
Terminal=false
StartupNotify=true
EOF
#
mkdir -p  ~/kali-arm64/home/kali/.config/xfce4/panel/launcher-6
cat <<EOF > ~/kali-arm64/home/kali/.config/xfce4/panel/launcher-6/16915437972.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Chromium Web Browser
Comment=Access the Internet
Exec=/usr/bin/chromium --no-sandbox %U
Icon=chromium
Path=
Terminal=false
StartupNotify=true
EOF
#
mkdir -p  ~/kali-arm64/home/kali/.config/xfce4/panel/launcher-7
cat <<EOF > ~/kali-arm64/home/kali/.config/xfce4/panel/launcher-7/16915415172.desktop
[Desktop Entry]
Version=1.0
Type=Application
Exec=exo-open --launch TerminalEmulator
Icon=org.xfce.terminalemulator
StartupNotify=true
Terminal=false
Categories=Utility;X-XFCE;X-Xfce-Toplevel;
OnlyShowIn=XFCE;
X-AppStream-Ignore=True
Name=Terminal Emulator
Comment=Use the command line
X-XFCE-Source=file:///usr/share/applications/xfce4-terminal-emulator.desktop
EOF
########################################
############## Desktop ##############
rm -rf ~/kali-arm64/home/kali/.config/xfce4/xfconf/xfce-perchannel-xml
mkdir -p ~/kali-arm64/home/kali/.config/xfce4/xfconf/xfce-perchannel-xml
cat <<EOF > ~/kali-arm64/home/kali/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
<?xml version="1.0" encoding="UTF-8"?>

<channel name="xfce4-panel" version="1.0">
  <property name="configver" type="int" value="2"/>
  <property name="panels" type="array">
    <value type="int" value="1"/>
    <property name="panel-1" type="empty">
      <property name="position" type="string" value="p=6;x=0;y=0"/>
      <property name="length" type="uint" value="100"/>
      <property name="position-locked" type="bool" value="true"/>
      <property name="size" type="uint" value="28"/>
      <property name="plugin-ids" type="array">
        <value type="int" value="1"/>
        <value type="int" value="2"/>
        <value type="int" value="3"/>
        <value type="int" value="4"/>
        <value type="int" value="5"/>
        <value type="int" value="6"/>
        <value type="int" value="7"/>
        <value type="int" value="8"/>
        <value type="int" value="900"/>
        <value type="int" value="10"/>
        <value type="int" value="11"/>
        <value type="int" value="12"/>
        <value type="int" value="14"/>
        <value type="int" value="16"/>
        <value type="int" value="17"/>
        <value type="int" value="19"/>
        <value type="int" value="20"/>
        <value type="int" value="21"/>
        <value type="int" value="2200"/>
      </property>
      <property name="icon-size" type="uint" value="22"/>
    </property>
  </property>
  <property name="plugins" type="empty">
    <property name="plugin-1" type="string" value="whiskermenu"/>
    <property name="plugin-2" type="string" value="separator"/>
    <property name="plugin-3" type="string" value="showdesktop"/>
    <property name="plugin-4" type="string" value="directorymenu">
      <property name="icon-name" type="string" value="system-file-manager"/>
      <property name="base-directory" type="string" value="/home/kali"/>
    </property>
    <property name="plugin-5" type="string" value="launcher">
      <property name="items" type="array">
        <value type="string" value="16915437661.desktop"/>
      </property>
    </property>
    <property name="plugin-6" type="string" value="launcher">
      <property name="items" type="array">
        <value type="string" value="16915437972.desktop"/>
      </property>
    </property>
    <property name="plugin-7" type="string" value="launcher">
      <property name="items" type="array">
        <value type="string" value="16915415172.desktop"/>
      </property>
      <property name="move-first" type="bool" value="true"/>
    </property>
    <property name="plugin-8" type="string" value="separator"/>
    <property name="plugin-9" type="string" value="pager">
      <property name="miniature-view" type="bool" value="false"/>
    </property>
    <property name="plugin-900" type="string" value="pager">
      <property name="miniature-view" type="bool" value="true"/>
      <property name="rows" type="uint" value="2"/>
    </property>
    <property name="plugin-10" type="string" value="separator"/>
    <property name="plugin-11" type="string" value="tasklist">
      <property name="show-handle" type="bool" value="false"/>
      <property name="show-labels" type="bool" value="false"/>
      <property name="middle-click" type="uint" value="1"/>
      <property name="grouping" type="uint" value="1"/>
    </property>
    <property name="plugin-12" type="string" value="separator">
      <property name="expand" type="bool" value="true"/>
      <property name="style" type="uint" value="0"/>
    </property>
    <property name="plugin-13" type="string" value="cpugraph"/>
    <property name="plugin-14" type="string" value="systray">
      <property name="size-max" type="uint" value="22"/>
      <property name="square-icons" type="bool" value="true"/>
      <property name="symbolic-icons" type="bool" value="false"/>
    </property>
    <property name="plugin-16" type="string" value="pulseaudio">
      <property name="enable-keyboard-shortcuts" type="bool" value="true"/>
    </property>
    <property name="plugin-17" type="string" value="notification-plugin"/>
    <property name="plugin-19" type="string" value="clock">
      <property name="digital-layout" type="uint" value="3"/>
      <property name="digital-time-format" type="string" value="%_H:%M"/>
      <property name="digital-time-font" type="string" value="Cantarell 11"/>
    </property>
    <property name="plugin-20" type="string" value="separator">
      <property name="style" type="uint" value="0"/>
    </property>
    <property name="plugin-21" type="string" value="separator"/>
    <property name="plugin-22" type="string" value="actions">
      <property name="appearance" type="uint" value="0"/>
      <property name="items" type="array">
        <value type="string" value="+lock-screen"/>
        <value type="string" value="-switch-user"/>
        <value type="string" value="-separator"/>
        <value type="string" value="-suspend"/>
        <value type="string" value="-hibernate"/>
        <value type="string" value="-hybrid-sleep"/>
        <value type="string" value="-separator"/>
        <value type="string" value="-shutdown"/>
        <value type="string" value="-restart"/>
        <value type="string" value="-separator"/>
        <value type="string" value="+logout"/>
        <value type="string" value="-logout-dialog"/>
      </property>
    </property>
    <property name="plugin-2200" type="string" value="actions">
      <property name="appearance" type="uint" value="0"/>
      <property name="items" type="array">
        <value type="string" value="-lock-screen"/>
        <value type="string" value="-switch-user"/>
        <value type="string" value="-separator"/>
        <value type="string" value="-suspend"/>
        <value type="string" value="-hibernate"/>
        <value type="string" value="-hybrid-sleep"/>
        <value type="string" value="-separator"/>
        <value type="string" value="-shutdown"/>
        <value type="string" value="-restart"/>
        <value type="string" value="-separator"/>
        <value type="string" value="+logout"/>
        <value type="string" value="-logout-dialog"/>
      </property>
    </property>
  </property>
</channel>
EOF
#

cat <<EOF > ~/kali-arm64/home/kali/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
<?xml version="1.0" encoding="UTF-8"?>

<channel name="xfce4-desktop" version="1.0">
  <property name="desktop-icons" type="empty">
    <property name="style" type="empty"/>
    <property name="file-icons" type="empty">
      <property name="show-home" type="empty"/>
      <property name="show-filesystem" type="empty"/>
      <property name="show-removable" type="empty"/>
      <property name="show-trash" type="empty"/>
    </property>
    <property name="icon-size" type="empty"/>
    <property name="tooltip-size" type="empty"/>
  </property>
  <property name="backdrop" type="empty">
    <property name="screen0" type="empty">
      <property name="monitor0" type="empty">
        <property name="image-path" type="empty"/>
        <property name="image-style" type="empty"/>
        <property name="image-show" type="empty"/>
      </property>
      <property name="monitor1" type="empty">
        <property name="image-path" type="empty"/>
        <property name="image-style" type="empty"/>
        <property name="image-show" type="empty"/>
      </property>
      <property name="monitor2" type="empty">
        <property name="image-path" type="empty"/>
        <property name="image-style" type="empty"/>
        <property name="image-show" type="empty"/>
      </property>
      <property name="monitor3" type="empty">
        <property name="image-path" type="empty"/>
        <property name="image-style" type="empty"/>
        <property name="image-show" type="empty"/>
      </property>
      <property name="monitor4" type="empty">
        <property name="image-path" type="empty"/>
        <property name="image-style" type="empty"/>
        <property name="image-show" type="empty"/>
      </property>
      <property name="monitorVNC-0" type="empty">
        <property name="workspace0" type="empty">
          <property name="color-style" type="int" value="0"/>
          <property name="image-style" type="int" value="5"/>
          <property name="last-image" type="string" value="/usr/share/backgrounds/kali-16x9/kali-red-sticker.jpg"/>
        </property>
        <property name="workspace1" type="empty">
          <property name="color-style" type="int" value="0"/>
          <property name="image-style" type="int" value="5"/>
          <property name="last-image" type="string" value="/usr/share/backgrounds/kali-16x9/default"/>
        </property>
        <property name="workspace2" type="empty">
          <property name="color-style" type="int" value="0"/>
          <property name="image-style" type="int" value="5"/>
          <property name="last-image" type="string" value="/usr/share/backgrounds/kali-16x9/default"/>
        </property>
        <property name="workspace3" type="empty">
          <property name="color-style" type="int" value="0"/>
          <property name="image-style" type="int" value="5"/>
          <property name="last-image" type="string" value="/usr/share/backgrounds/kali-16x9/default"/>
        </property>
      </property>
    </property>
  </property>
  <property name="last" type="empty">
    <property name="window-width" type="int" value="639"/>
    <property name="window-height" type="int" value="544"/>
  </property>
</channel>
EOF
############################################################
}

create_launcher
sound_setup


printf "\n${blue}          Configuring NetHunter for Termux ...\n"
printf "\e[5;31m               Tunggu Beberapa Menit... 👌\n"
sleep 1.4
printf "\e[0m "
clear
fix_profile_bash
fix_sudo
if [ -f "${PREFIX}/bin/nh" ]; then
    create_launcher
else
    echo "Error"
fi

fix_uid
nh rm /bin/kali-motd &> /dev/null
nh rm /bin/kernel-install &> /dev/null

rm ~/kali-arm64/etc/apt/sources.list
echo "deb https://ftp.debian.org/debian stable main contrib non-free non-free-firmware" >> ~/kali-arm64/etc/apt/sources.list
echo "deb https://mirror.primelink.net.id/kali kali-rolling main contrib non-free" >> ~/kali-arm64/etc/apt/sources.list
rm ~/kali-arm64/etc/resolv.conf
echo "nameserver 8.8.8.8" >> ~/kali-arm64/etc/resolv.conf
nh -r apt update
nh echo "Asia/Jakarta" | sudo tee /etc/timezone
nh -r dpkg-reconfigure --frontend noninteractive tzdata
#nh -r apt-get install git wget -y 2>/dev/null
fire(){
if ask "Install Firefox" "N"; then
nh -r apt-get install firefox-esr -y 

nh mkdir -p /home/kali/Desktop
nh cat <<EOF > ~/kali-arm64/home/kali/Desktop/firefox-esr.desktop
[Desktop Entry]
Version=1.0
Name=Firefox ESR Web Browser
Exec=/usr/bin/firefox-esr %u
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=firefox-esr
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml_xml;application/x-mimearchive;x-scheme-handler/http;x-scheme-handler/https;
StartupWMClass=Firefox-esr
StartupNotify=true
Keywords=browser
EOF
chmod 700 ~/kali-arm64/home/kali/Desktop/firefox-esr.desktop
else
printf "\033[33mOkeh\n"
fi
}
chrom(){
if ask "Install Chromium" "N"; then
nh -r apt install chromium -y 
cat <<EOF > ~/kali-arm64/home/kali/Desktop/chromium.desktop
[Desktop Entry]
Version=1.0
Name=Browser Web Chromium
Exec=/usr/bin/chromium --no-sandbox %U
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=chromium
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml_xml;application/x-mimearchive;x-scheme-handler/http;x-scheme-handler/https;
StartupWMClass=chromium
StartupNotify=true
Keywords=browser
EOF
chmod 700 ~/kali-arm64/home/kali/Desktop/chromium.desktop
else
printf "\033[33mOkeh\n"
fi
}
    if ask "Install Vncserver dan Dekstop xfce4" "N"; then
nh -r sudo apt-get -f install
nh -r apt install dbus-x11 tigervnc-standalone-server -y
nh -r apt install xfce4 gnome-terminal xfce4-whiskermenu-plugin -y
echo '#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export SHELL=/bin/bash
startxfce4' >> ~/kali-arm64/home/kali/.vnc/xstartup
nh chmod +x .vnc/xstartup
fire
chrom
panels
else
printf "\n\033[33mOkeh\n${reset}"
fi


#




create_kex_launcher
#echo "123456" | vncpasswd -f > ~/kali-arm64/home/kali/.vnc/passwd > /dev/null 2>&1
#echo "123456" | vncpasswd -f > ~/kali-arm64/root/.vnc/passwd > /dev/null 2>&1
sleep 1

cd
clear
printf "\033[5;33m                  Nanti Atur² Sendiri Ya😄\n"
sleep 5
clear

printf "\e[5;34m╭─────────────────────────────────────────╮\n"
printf "\e[5;34m│\e[5;33m       Kali NetHunter for Termux         \e[5;34m│\n"
printf "\e[5;34m╰─────────────────────────────────────────╯\n"
printf "\e[6;34m      To start Kali NetHunter, type :⤦\e[0;m\n"
printf "\e[5;31m *\e[4;36m nh p pass   \e[5;0m \e[5;33m▶ Tetapkan kata Sandi Vnc\n"
printf "\e[5;31m *\e[4;36m nh p        \e[5;0m \e[5;33m▶ Start Vnc\n"
printf "\e[5;31m *\e[4;36m nh p s      \e[5;0m \e[5;33m▶ Stop Vnc\n"
printf "\e[5;31m *\e[4;36m nh -r       \e[5;0m \e[5;33m▶ Start Nethunter Root\n"
printf "\e[5;31m *\e[4;36m nh          \e[5;0m \e[5;33m▶ Start Nethunter\n"
printf "\e[5;34m╭─────────────────────────────────────────╮\n"

printf "\r"
printf "\e[5;0m \e[5;33m[+] 123456 Password untuk VNCSERVER\e[5;0m\n"
printf "\e[5;0m \e[5;33m[+] Ketikan (ctrl + z) Kalau Susah Keluar\e[5;0m\n"
printf "\e[5;34m╰─────────────────────────────────────────╯\n"
rm -rf ~/$Home/kali-nethunter
